all:
  children:
    webservers:
      hosts:
        web1.ru-central1.internal:
        web2.ru-central1.internal:
    zabbix_server:
      hosts:
        zabbix.ru-central1.internal:
    elasticsearch_server:
      hosts:
        elasticsearch.ru-central1.internal:
    kibana_server:
      hosts:
        kibana.ru-central1.internal:
    all:
      hosts:
        bastion.ru-central1.internal:
        zabbix.ru-central1.internal:
        elasticsearch.ru-central1.internal:
        kibana.ru-central1.internal:
        web1.ru-central1.internal:
        web2.ru-central1.internal:
  vars:
    ansible_user: ubuntu
